cloud:
  aws:
    credentials:
      access-key: "xxx-xxx-xxxx"
      secret-key: "xxx-xxx-xxxx"
    region:
      static: us-east-2
    stack:
      auto: false

application:
  bucket:
    name: amazons3storage


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9091

